"""
Django settings for GPT project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ye-$ay&(&4jay1z))-eyneow2or)l_rw+_sd+l^s800yv%q=#i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '127.0.0.1',
    '192.168.1.8',
    'https://192.168.1.8'
    '*',
    '192.168.55.91',
    'https://192.168.55.91',
    'http://192.168.55.91',
    'https://192.168.7.168',
    '192.168.7.168',
    '192.168.0.132',
    'https://discoursegpt.onrender.com'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',


    #custon apps
    'APP',
    'api',
    'rest_framework',
    'corsheaders',
    # 'sslserver',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    
]

CORS_ALLOWED_ORIGINS = [
    "http://192.168.1.8:8080", # Adjust this to your Vue.js application's origin
    "http://192.168.1.6:8080", # Adjust this to your Vue.js application's origin
    "http://localhost:8080",
     "http://localhost:8080",  # Add your frontend URL
    "http://127.0.0.1:8080",  # Add your frontend URL with IP
    "http://localhost:8000",  # Add your Django development server URL
    "http://127.0.0.1:8000", # Adjust this to your Vue.js application's origin
    'capacitor://np.com.prithaklamsal.discoursegpt',
    'http://192.168.1.5',
    'http://192.168.1.1',
    'http://*',
    'https://*',
    'capacitor://*',
    'http://192.168.1.6:8000',
    'http://192.168.1.5',
    'https://192.168.1.8:8000',
    'https://192.168.55.91:8080',
    'https://localhost:8080',
    'https://192.168.7.168:8080',
    'https://192.168.0.132:8080'
    # '*',


]

CORS_ALLOWED_HEADERS = [
    'access-control-allow-headers',
    'access-control-allow-origin'
    'access-allow-control-origin',
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'content-disposition',  # Add this line
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_HEADERS = True
CORS_ALLOW_ALL_ORIGINS=True

# SSLCERTIFICATE = 'certificate.pem'
# SSLPRIVATEKEY = 'privatekey.pem'


ROOT_URLCONF = 'GPT.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'GPT.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

